@AspAplication_HostAddress = https://localhost:7131

### Crear tarea async
POST {{AspAplication_HostAddress}}/api/tasks
Content-Type: application/json

{
  "title": "Probar async",
  "description": "La API ya usa async y await"
}
### Ver todas
GET {{AspAplication_HostAddress}}/api/tasks

### Ver por ID
GET {{AspAplication_HostAddress}}/api/tasks/2

### Editar tarea
PUT {{AspAplication_HostAddress}}/api/tasks/2
Content-Type: application/json

{
  "title": "Probar async actualizado",
  "description": "PUT también usa async"
}

### Completar tarea
PUT {{AspAplication_HostAddress}}/api/tasks/2/complete

### Borrar tarea
DELETE {{AspAplication_HostAddress}}/api/tasks/2